'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------


Imports Microsoft.VisualBasic
	Imports System
Namespace My


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()> _
	Friend Class Resources

		Private Shared resourceMan As Global.System.Resources.ResourceManager

		Private Shared resourceCulture As Global.System.Globalization.CultureInfo

		<Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")> _
		Friend Sub New()
		End Sub

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If Object.ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
		Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Large.
		''' </summary>
		Friend Shared ReadOnly Property MyEnum_Large() As String
			Get
				Return ResourceManager.GetString("MyEnum_Large", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Medium.
		''' </summary>
		Friend Shared ReadOnly Property MyEnum_Medium() As String
			Get
				Return ResourceManager.GetString("MyEnum_Medium", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to Small.
		''' </summary>
		Friend Shared ReadOnly Property MyEnum_Small() As String
			Get
				Return ResourceManager.GetString("MyEnum_Small", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
		'''&lt;root&gt;
		'''  &lt;!-- 
		'''    Microsoft ResX Schema 
		'''    
		'''    Version 2.0
		'''    
		'''    The primary goals of this format is to allow a simple XML format 
		'''    that is mostly human readable. The generation and parsing of the 
		'''    various data types are done through the TypeConverter classes 
		'''    associated with the data types.
		'''    
		'''    Example:
		'''    
		'''    ... ado.net/XML headers &amp; schema ...
		'''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
		'''    &lt;resheader n [rest of string was truncated]&quot;;.
		''' </summary>
		Friend Shared ReadOnly Property Resources_fr() As String
			Get
				Return ResourceManager.GetString("Resources_fr", resourceCulture)
			End Get
		End Property

		''' <summary>
		'''   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
		'''&lt;root&gt;
		'''  &lt;!-- 
		'''    Microsoft ResX Schema 
		'''    
		'''    Version 2.0
		'''    
		'''    The primary goals of this format is to allow a simple XML format 
		'''    that is mostly human readable. The generation and parsing of the 
		'''    various data types are done through the TypeConverter classes 
		'''    associated with the data types.
		'''    
		'''    Example:
		'''    
		'''    ... ado.net/XML headers &amp; schema ...
		'''    &lt;resheader name=&quot;resmimetype&quot;&gt;text/microsoft-resx&lt;/resheader&gt;
		'''    &lt;resheader n [rest of string was truncated]&quot;;.
		''' </summary>
		Friend Shared ReadOnly Property Resources_ru() As String
			Get
				Return ResourceManager.GetString("Resources_ru", resourceCulture)
			End Get
		End Property
	End Class
End Namespace
